<script setup lang="ts">
const entries = [
  { icon: '👨‍👩‍👧', title: '家庭成员与权限', subtitle: '邀请家人和朋友，配置可访问的功能', tone: 'leaf' },
  { icon: '📮', title: '家庭待办', subtitle: '清洗空调、补充物资等日常安排', tone: 'sky' },
  { icon: '💡', title: '收藏与灵感', subtitle: '收下想做的菜、想去的地方', tone: 'sun' },
  { icon: '📚', title: '家庭档案', subtitle: '一起留下值得记住的小事', tone: 'rose' },
  { icon: '⚙️', title: '设置', subtitle: '家庭资料、消息提醒和账号信息', tone: 'stone' },
];
function open(title: string) { uni.showToast({ title: `${title}将在下一迭代接入`, icon: 'none' }); }
</script>
<template><view class="page"><view class="cloud cloud-one"></view><view class="cloud cloud-two"></view><view class="profile"><view class="home">🏠</view><view><text class="kicker">我的家</text><text class="name">扣扣的家</text><text class="role">今天也把小日子过得暖暖的</text></view><view class="flower">🌼</view></view><view class="section"><text class="section-title">家里的小角落</text><text class="section-subtitle">有事慢慢记，大家一起做</text></view><view class="entries"><view v-for="entry in entries" :key="entry.title" class="entry" @tap="open(entry.title)"><view class="icon" :class="entry.tone">{{ entry.icon }}</view><view><text class="entry-title">{{ entry.title }}</text><text class="entry-subtitle">{{ entry.subtitle }}</text></view><text class="go">›</text></view></view><view class="footer">扣扣的家 · 把每一天收进回忆里</view></view></template>
<style scoped>.page{position:relative;min-height:100vh;padding:42rpx 28rpx 60rpx;overflow:hidden;background:linear-gradient(180deg,#dff0e1 0,#f7f3e8 38%)}.cloud{position:absolute;border-radius:999rpx;background:rgba(255,255,255,.38)}.cloud-one{top:45rpx;right:-45rpx;width:180rpx;height:64rpx}.cloud-two{top:112rpx;left:-70rpx;width:155rpx;height:54rpx}.profile{position:relative;display:flex;align-items:center;gap:18rpx;padding:28rpx;border:4rpx solid rgba(255,253,247,.75);border-radius:34rpx;background:rgba(255,253,247,.9);box-shadow:0 14rpx 30rpx rgba(87,124,86,.13)}.home{display:flex;align-items:center;justify-content:center;width:94rpx;height:94rpx;border-radius:32rpx;background:#b9ddaa;font-size:48rpx;transform:rotate(-4deg)}.kicker,.name,.role,.section-title,.section-subtitle,.entry-title,.entry-subtitle{display:block}.kicker{font-size:20rpx;letter-spacing:4rpx;color:#7a9b72}.name{margin-top:3rpx;font-size:37rpx;font-weight:700;color:#3d5941}.role{margin-top:7rpx;font-size:21rpx;color:#85967e}.flower{position:absolute;right:19rpx;top:14rpx;font-size:33rpx}.section{padding:42rpx 8rpx 18rpx}.section-title{font-size:31rpx;font-weight:700;color:#56614d}.section-subtitle{margin-top:8rpx;font-size:22rpx;color:#989181}.entries{display:grid;gap:15rpx}.entry{display:flex;align-items:center;gap:18rpx;padding:23rpx;border:3rpx solid #fffdf7;border-radius:26rpx;background:#fffdf7;box-shadow:0 7rpx 14rpx rgba(83,94,78,.05)}.entry:active{transform:scale(.985);background:#fff9ed}.icon{display:flex;align-items:center;justify-content:center;width:65rpx;height:65rpx;border-radius:23rpx;font-size:34rpx}.leaf{background:#dff0d2}.sky{background:#dcecfb}.sun{background:#fff0bd}.rose{background:#ffe0e5}.stone{background:#ede9e1}.entry-title{font-size:27rpx;color:#4d5849}.entry-subtitle{margin-top:6rpx;font-size:20rpx;color:#978f84}.go{margin-left:auto;font-size:40rpx;color:#c3b9aa}.footer{margin-top:45rpx;text-align:center;color:#aaa093;font-size:20rpx}</style>
