-- Generated from apps/api/prisma/schema.prisma with Prisma 6.0.0.
CREATE TYPE "MemberStatus" AS ENUM ('PENDING', 'ACTIVE', 'DISABLED', 'LEFT');
CREATE TYPE "PermissionLevel" AS ENUM ('VIEW', 'EDIT', 'MANAGE');
CREATE TYPE "TripStatus" AS ENUM ('PLANNING', 'PENDING', 'DEPARTING', 'COMPLETED', 'CANCELLED');
CREATE TYPE "RecipeStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "MealStatus" AS ENUM ('DRAFT', 'CONFIRMED', 'COOKING', 'COMPLETED', 'CANCELLED');
CREATE TYPE "ShoppingItemStatus" AS ENUM ('WISHLIST', 'NEXT_TRIP', 'REPLENISH', 'PURCHASED');
CREATE TYPE "InventoryTransactionType" AS ENUM ('STOCK_IN', 'CONSUME', 'ADJUST', 'EXPIRE');

CREATE TABLE "User" ("id" TEXT NOT NULL, "openId" TEXT NOT NULL, "nickname" TEXT, "avatarUrl" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Household" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Household_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Membership" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "userId" TEXT NOT NULL, "status" "MemberStatus" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Membership_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Role" ("id" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, CONSTRAINT "Role_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MemberRole" ("membershipId" TEXT NOT NULL, "roleId" TEXT NOT NULL, CONSTRAINT "MemberRole_pkey" PRIMARY KEY ("membershipId","roleId"));
CREATE TABLE "ModulePermission" ("id" TEXT NOT NULL, "membershipId" TEXT NOT NULL, "module" TEXT NOT NULL, "level" "PermissionLevel" NOT NULL, CONSTRAINT "ModulePermission_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Trip" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "title" TEXT NOT NULL, "status" "TripStatus" NOT NULL DEFAULT 'PLANNING', "startsAt" TIMESTAMP(3) NOT NULL, "endsAt" TIMESTAMP(3), "destination" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Trip_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TripMember" ("tripId" TEXT NOT NULL, "membershipId" TEXT NOT NULL, "canEdit" BOOLEAN NOT NULL DEFAULT false, "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TripMember_pkey" PRIMARY KEY ("tripId","membershipId"));
CREATE TABLE "RecipeCategory" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "name" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "RecipeCategory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Ingredient" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "name" TEXT NOT NULL, "defaultUnit" TEXT NOT NULL, CONSTRAINT "Ingredient_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Recipe" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "categoryId" TEXT, "name" TEXT NOT NULL, "status" "RecipeStatus" NOT NULL DEFAULT 'DRAFT', "coverObjectKey" TEXT, "steps" JSONB NOT NULL, "createdById" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Recipe_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecipeIngredient" ("recipeId" TEXT NOT NULL, "ingredientId" TEXT NOT NULL, "quantity" DECIMAL(12,3), "unit" TEXT NOT NULL, "optional" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "RecipeIngredient_pkey" PRIMARY KEY ("recipeId","ingredientId"));
CREATE TABLE "RecipeSeasoning" ("id" TEXT NOT NULL, "recipeId" TEXT NOT NULL, "name" TEXT NOT NULL, CONSTRAINT "RecipeSeasoning_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InventoryItem" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "ingredientId" TEXT NOT NULL, "quantity" DECIMAL(12,3) NOT NULL, "unit" TEXT NOT NULL, "expiresAt" TIMESTAMP(3), "location" TEXT, CONSTRAINT "InventoryItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InventoryTransaction" ("id" TEXT NOT NULL, "inventoryItemId" TEXT NOT NULL, "type" "InventoryTransactionType" NOT NULL, "quantityDelta" DECIMAL(12,3) NOT NULL, "reason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InventoryTransaction_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Meal" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "scheduledAt" TIMESTAMP(3) NOT NULL, "mealType" TEXT NOT NULL, "status" "MealStatus" NOT NULL DEFAULT 'DRAFT', CONSTRAINT "Meal_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MealItem" ("id" TEXT NOT NULL, "mealId" TEXT NOT NULL, "recipeId" TEXT NOT NULL, "addedById" TEXT NOT NULL, "note" TEXT, CONSTRAINT "MealItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ShoppingList" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "name" TEXT NOT NULL, CONSTRAINT "ShoppingList_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ShoppingItem" ("id" TEXT NOT NULL, "listId" TEXT NOT NULL, "name" TEXT NOT NULL, "quantity" DECIMAL(12,3), "unit" TEXT, "status" "ShoppingItemStatus" NOT NULL DEFAULT 'NEXT_TRIP', "sourceType" TEXT NOT NULL, "sourceId" TEXT, CONSTRAINT "ShoppingItem_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_openId_key" ON "User"("openId");
CREATE UNIQUE INDEX "Membership_householdId_userId_key" ON "Membership"("householdId", "userId");
CREATE UNIQUE INDEX "Role_code_key" ON "Role"("code");
CREATE UNIQUE INDEX "ModulePermission_membershipId_module_key" ON "ModulePermission"("membershipId", "module");
CREATE INDEX "RecipeCategory_householdId_sortOrder_idx" ON "RecipeCategory"("householdId", "sortOrder");
CREATE UNIQUE INDEX "RecipeCategory_householdId_name_key" ON "RecipeCategory"("householdId", "name");
CREATE UNIQUE INDEX "Ingredient_householdId_name_key" ON "Ingredient"("householdId", "name");
CREATE INDEX "Recipe_householdId_status_categoryId_idx" ON "Recipe"("householdId", "status", "categoryId");
CREATE UNIQUE INDEX "RecipeSeasoning_recipeId_name_key" ON "RecipeSeasoning"("recipeId", "name");
CREATE INDEX "InventoryItem_householdId_expiresAt_idx" ON "InventoryItem"("householdId", "expiresAt");
CREATE INDEX "InventoryTransaction_inventoryItemId_createdAt_idx" ON "InventoryTransaction"("inventoryItemId", "createdAt");
CREATE INDEX "Meal_householdId_scheduledAt_idx" ON "Meal"("householdId", "scheduledAt");
CREATE UNIQUE INDEX "MealItem_mealId_recipeId_addedById_key" ON "MealItem"("mealId", "recipeId", "addedById");
CREATE INDEX "ShoppingList_householdId_idx" ON "ShoppingList"("householdId");
CREATE INDEX "ShoppingItem_listId_status_idx" ON "ShoppingItem"("listId", "status");

ALTER TABLE "Membership" ADD CONSTRAINT "Membership_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MemberRole" ADD CONSTRAINT "MemberRole_membershipId_fkey" FOREIGN KEY ("membershipId") REFERENCES "Membership"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MemberRole" ADD CONSTRAINT "MemberRole_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ModulePermission" ADD CONSTRAINT "ModulePermission_membershipId_fkey" FOREIGN KEY ("membershipId") REFERENCES "Membership"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Trip" ADD CONSTRAINT "Trip_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TripMember" ADD CONSTRAINT "TripMember_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TripMember" ADD CONSTRAINT "TripMember_membershipId_fkey" FOREIGN KEY ("membershipId") REFERENCES "Membership"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecipeCategory" ADD CONSTRAINT "RecipeCategory_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Ingredient" ADD CONSTRAINT "Ingredient_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Recipe" ADD CONSTRAINT "Recipe_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Recipe" ADD CONSTRAINT "Recipe_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "RecipeCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RecipeIngredient" ADD CONSTRAINT "RecipeIngredient_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "Recipe"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecipeIngredient" ADD CONSTRAINT "RecipeIngredient_ingredientId_fkey" FOREIGN KEY ("ingredientId") REFERENCES "Ingredient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecipeSeasoning" ADD CONSTRAINT "RecipeSeasoning_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "Recipe"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InventoryItem" ADD CONSTRAINT "InventoryItem_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InventoryItem" ADD CONSTRAINT "InventoryItem_ingredientId_fkey" FOREIGN KEY ("ingredientId") REFERENCES "Ingredient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InventoryTransaction" ADD CONSTRAINT "InventoryTransaction_inventoryItemId_fkey" FOREIGN KEY ("inventoryItemId") REFERENCES "InventoryItem"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Meal" ADD CONSTRAINT "Meal_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MealItem" ADD CONSTRAINT "MealItem_mealId_fkey" FOREIGN KEY ("mealId") REFERENCES "Meal"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MealItem" ADD CONSTRAINT "MealItem_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "Recipe"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ShoppingList" ADD CONSTRAINT "ShoppingList_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShoppingItem" ADD CONSTRAINT "ShoppingItem_listId_fkey" FOREIGN KEY ("listId") REFERENCES "ShoppingList"("id") ON DELETE CASCADE ON UPDATE CASCADE;
